courts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('schedule/', views.ScheduleView.as_view(), name="schedule"),
    path('reservation/<int:year>/<int:month>/<int:day>/<int:hour>/', views.ReserveView.as_view(),
         name="reserve_court"),
    path('cancel_reservation/<int:reservation_id>/', views.CancelReservationView.as_view(), name="cancel_reservation"),
    path('notification/<slug:category_slug>/<int:year>/<int:month>/<int:day>/<int:hour>/',
         views.AddNotificationView.as_view(), name="add_notification"),
]

squash_club/urls.py
from django.contrib import admin
from django.urls import path, include

from courts.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('courts/', include('courts.urls')),
    path('payment/', include('payment.urls')),
    path('', LandingPageView.as_view(), name='landing_page'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name="logout"),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('user_profile/', views.UserProfileView.as_view(), name='user_profile'),
]

courts/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models

from courts.fields import OrderField
from squash_club import settings


class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name="Nazwa")
    slug = models.SlugField(max_length=32, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "kategorię"
        verbose_name_plural = "Kategorie"


class Court(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="courts", verbose_name="Kategoria")
    order = OrderField(blank=True, for_fields=['category'], verbose_name="Numer kortu", unique=True)
    air_condition = models.BooleanField(default=False, verbose_name="Klimatyzacja")
    lighting = models.BooleanField(default=True, verbose_name="Oświetlenie")

    def __str__(self):
        return f"Kort nr {self.order}"

    class Meta:
        verbose_name = "kort"
        verbose_name_plural = "Korty"
        ordering = ("order",)


class PriceList(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="prices", verbose_name="Kategoria")
    weekend = models.BooleanField(default=False)
    time = models.IntegerField(choices=[(x, datetime.time(x)) for x in range(0, 24)],
                               verbose_name="Godzina", null=True, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Cena")

    def __str__(self):
        return f"{self.category}: plan cenowy na godzinę {self.time} {'w weekend' if self.weekend else ''}"

    class Meta:
        verbose_name = "cennik"
        verbose_name_plural = "Plany cenowe"
        constraints = [models.UniqueConstraint(fields=["category", "weekend", "time"], name="unique_price")]
        ordering = ["category", "weekend", "time"]

    def clean(self):
        if self.weekend and self.time:
            raise ValidationError("Cena weekendowa obowiązuje przez cały dzień. Nie podawaj godziny.")
        if not self.weekend and not self.time:
            raise ValidationError("Cena w tygodniu nie jest jednakowa w ciągu dnia. Uzupełnij godzinę.")


class Reservation(models.Model):
    court = models.ForeignKey(Court, on_delete=models.CASCADE, related_name="reservations", verbose_name="Kort")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Użytkownik")
    date = models.DateField(verbose_name="Data rezerwacji")
    time = models.TimeField(verbose_name="Godzina rezerwacji")
    duration = models.PositiveIntegerField(verbose_name="Czas rezerwacji", default=1)
    discount = models.ForeignKey("Discount",
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank="True",
                                 verbose_name="Zniżka",
                                 related_name="reservations")
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Cena")
    paid = models.BooleanField(default=False, verbose_name="Opłacone")
    status = models.BooleanField(default=False, verbose_name="Status")
    comment = models.TextField(verbose_name="Komentarz", null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    braintree_id = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return f"Rezerwacja nr {self.id}"

    class Meta:
        verbose_name = "rezerwacja"
        verbose_name_plural = "Rezerwacje"
        constraints = [models.UniqueConstraint(fields=["court", "date", "time"], name="unique_reservation")]
        ordering = ["-date", "-time", "id"]


class Discount(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoria", related_name="discounts")
    name = models.CharField(max_length=32, verbose_name="Nazwa")
    discount = models.PositiveIntegerField(verbose_name="Zniżka")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "zniżka"
        verbose_name_plural = "Zniżki"


class Notification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Użytkownik")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoria")
    date = models.DateTimeField(verbose_name="Data")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")

    def __str__(self):
        return f"Powiadomienie dla użytkownika {self.user.username} o zwolnieniu kortu do {self.category} " \
               f"w terminie {self.date}"

    class Meta:
        verbose_name = "powiadomienie"
        verbose_name_plural = "Powiadomienia"
        ordering = ['-date', 'created']

courts/forms.py
import django.forms as forms

from courts.models import Court, Discount
from courts.validators import validate_phone_number


class ReserveCourtForm(forms.Form):
    court = forms.ModelChoiceField(Court.objects.all(), empty_label=None)
    discount = forms.ModelChoiceField(Discount.objects.all(), required=False)
    comment = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, date, time, *args, **kwargs):
        super(ReserveCourtForm, self).__init__(*args, **kwargs)
        self.fields['court'].queryset = Court.objects.exclude(reservations__date=date, reservations__time=time)


class AddPhoneNumberForm(forms.Form):
    phone_number = forms.CharField(max_length=12, label="Numer telefonu", validators=[validate_phone_number])

courts/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View

from courts.forms import ReserveCourtForm, AddPhoneNumberForm
from courts.models import Reservation, PriceList, Court, Notification, Category, Discount
from courts.tasks import reservation_confirm, send_sms_notification
from users.models import Profile

User = get_user_model()


class LandingPageView(View):
    def get(self, request):
        return render(request, 'landing_page.html', {})


class ScheduleView(View):
    def get(self, request):
        present = datetime.date.today()
        dates = []
        day = datetime.timedelta(days=1)
        for i in range(7):
            dates.append(present + i * day)
        prices = PriceList.objects.filter(weekend=False)
        weekend_price = PriceList.objects.get(weekend=True)
        return render(request, 'schedule.html', {"dates": dates, "prices": prices, "weekend_price": weekend_price})


class ReserveView(View):
    def get(self, request, year, month, day, hour):
        date = datetime.date(year, month, day)
        time = datetime.time(hour)
        form = ReserveCourtForm(date, time)
        if date.strftime("%A") in ["Sobota", "Niedziela"]:
            price = PriceList.objects.get(weekend=True)
        else:
            price = PriceList.objects.get(time=time.strftime("%-H"))

        if request.is_ajax():
            discount = Discount.objects.get(pk=request.GET['discount'])
            price_after_discount = max(price.price - discount.discount, 0)
            return JsonResponse({"total_price": price_after_discount})

        return render(request, 'reserve_court.html', {'form': form, 'date': date, 'time': time, 'price': price})

    def post(self, request, year, month, day, hour):
        date = datetime.date(year, month, day)
        time = datetime.time(hour)
        user = request.user
        form = ReserveCourtForm(date, time, request.POST)
        if date.strftime("%A") in ["Sobota", "Niedziela"]:
            price = PriceList.objects.get(weekend=True)
        else:
            price = PriceList.objects.get(time=time.strftime("%-H"))
        if form.is_valid():
            court = form.cleaned_data['court']
            discount = form.cleaned_data['discount']
            comment = form.cleaned_data['comment']
            if discount:
                total_price = price.price - discount.discount
            else:
                total_price = price.price
            reservation = Reservation.objects.create(
                court=court,
                user=user,
                date=date,
                time=time,
                # duration=duration,
                price=total_price,
                comment=comment
            )
            reservation_confirm.delay(reservation.id)
            request.session['reservation_id'] = reservation.id
            return redirect('payment_process')
            # return render(request, "reservation_confirm.html", {'reservation': reservation})
        else:
            return render(request, 'reserve_court.html', {'form': form, 'date': date, 'time': time, 'price': price})


class CancelReservationView(View):
    def post(self, request, reservation_id):
        reservation = Reservation.objects.get(pk=reservation_id)
        user = request.user
        now = datetime.datetime.now()
        date = reservation.date
        time = reservation.time
        if user == reservation.user and now + datetime.timedelta(hours=24) <= datetime.datetime.combine(
                date, time):
            if not Court.objects.exclude(reservations__date=date, reservations__time=time):
                notification = Notification.objects.filter(date=datetime.datetime.combine(date, time)).first()
                if notification:
                    send_sms_notification.delay(notification.id)
                    notification.delete()
            reservation.delete()
        else:
            messages.warning(request,
                             "Nie można anulować tej rezerwacji "
                             "- zostało mniej niż 24 godziny lub użytkownik nie ma uprawnień")
        return redirect('user_profile')


class AddNotificationView(View):
    def get(self, request, category_slug, year, month, day, hour):
        date = datetime.date(year, month, day)
        time = datetime.time(hour)
        user = request.user
        form = AddPhoneNumberForm(initial={"phone_number": user.profile.phone_number})
        return render(request, 'notification_form.html', {"date": date, "time": time, "form": form})

    def post(self, request, category_slug, year, month, day, hour):
        date = datetime.date(year, month, day)
        time = datetime.time(hour)
        category = Category.objects.get(slug=category_slug)
        user = request.user
        profile = Profile.objects.get(user=user)
        form = AddPhoneNumberForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']
            if phone_number != user.profile.phone_number:
                profile.phone_number = phone_number
                profile.save()
            Notification.objects.create(user=user, category=category, date=datetime.datetime.combine(date, time))
            messages.info(request, "Powiadomimy Cię, jak tylko zwolni się kort w wybranym przez Ciebie terminie.")
        return redirect('schedule')

courts/templates/landing_page.html
{% extends 'base.html' %}
{% block title %}
Squash Club
{% endblock %}
{% block content %}
<h1>Witaj na stronie Squash Club</h1>
{% endblock %}

courts/templates/notification_form.html
{% extends 'base.html' %}
{% block title %}
WYślij powiadomienie
{% endblock %}
{% block content %}
<h1>Wyślij powiadomienie</h1>
    <p>{{ date|date:"l d E Y" }}, g. {{ time }}</p>
    <hr/>
    <p>Brak wolnych kortów w wybranym terminie. Podaj swój numer telefonu, aby otrzymać powiadomienie,
        jeśli któryś z kortów się zwolni</p>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit" value="Potwierdź">
    </form>
{% endblock %}

courts/templates/reservation_confirm.html
{% extends 'base.html' %}
{% block title %}
Potwierdzenie rezerwacji
{% endblock %}
{% block content %}
<h1>Potwierdzenie rezerwacji</h1>
    <p>Rezerwacja nr {{ reservation.id }} na kort nr {{ reservation.court.order }} w dniu {{ reservation.date }}
    na godzinę {{ reservation.time }} została zrealizowana pomyślnie</p>
    <p>Powrót na <a href="">stronę główną</a></p>
    <p>Powrót na <a href="{% url 'schedule' %}">stronę rezerwacji</a></p>
{% endblock %}

courts/templates/reserve_court.html
{% extends 'base.html' %}
{% block title %}
    Rezerwacja kortu
{% endblock %}
{% block content %}
    <h1>Rezerwacja kortu na godzinę {{ time | time:"H:i" }} w dniu {{ date | date:"d E (l)" }}</h1>
    <p>Wybierz kort: </p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zarezerwuj - {{ price.price }} zł">
    </form>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
    $(document).ready(function() {
        let discount = $('#id_discount');
        let submit = $("input[type='submit']")

        discount.on('change', function() {
            $.ajax({
                url: "{% url 'reserve_court' date.year date.month date.day time.hour %}",
                data: $(this).serialize(),
                success: function (data) {
                    submit.val(`Zarezerwuj - ${data["total_price"]} zł`)
                },
            })
        })
    })
    </script>
{% endblock %}

courts/templates/schedule.html
{% extends 'base.html' %}
{% load courts_tags %}
{% block title %}
    Harmonogram
{% endblock %}

{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <table>
        <thead>
        <tr>
            <th></th>
            {% for date in dates %}
                <th>
                    {{ date | date:"d E Y" }} <br/>
                    {{ date | date:"l" }}
                </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for price in prices %}
            <tr>
                <td>{{ price.get_time_display | time:"H:i" }}</td>
                {% for date in dates %}
                    <td>
                        <button>
                            {% check_if_courts_reserved date price.get_time_display as courts_reserved %}
                            {% if courts_reserved %}
                                Brak wolnych kortów <br>
                                <a href="{% url 'add_notification' price.category.slug date.year date.month date.day price.get_time_display.hour %}">Wyślij
                                    powiadomienie</a>
                            {% else %}
                                <a href="{% url 'reserve_court' date.year date.month date.day price.get_time_display.hour %}">
                                    Rezerwuj <br>
                                    {% if date|date:"l" == "Sobota" or date|date:"l" == "Niedziela" %}
                                        {{ weekend_price.price }} zł
                                    {% else %}
                                        {{ price.price }} zł
                                    {% endif %}
                                </a>
                            {% endif %}
                        </button>
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}